sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf DMTN-070.pdf --upload --lsstdoc DMTN-070.tex --env=travis --ltd-product dmtn-070"
env:
  global:
    - secure: "K3MuY1RKD5EBHDt4IEcsM7V8lJ01MUhi/af5GGxCuPOcr7HHraW45hN+iSom2LKbN4aDp3gJoWNXsaS1lfTL6HUdTVgeiswAZeio5w0k0TBxPOzSvZ4zVHs2GecFSKOPpGBuGPFZgjSIYdoZjo/+5zxSkvx3vkXfbOW3kB3yIVVCqlvKlr4hP/VGnBG/MsCUOpECpSUUc17OHw4+sMkrTTi5gSBpAuaLubhrNzBsltksFllzWWV2D2t/b4CUuUXIcrCXKwfk3bXr0PJ8XFpQD/zLUiw5GlOg+8IOheVY+v06stPgE6gJ17zRyE5hWWjzagSRU625dH0f7nK18vO8fZaR0wsxs+W7srOzGLV3WIuFsjhWV08pADQvPnzJq+H+g9MMTl3mjtzh9kQ+B0m8Gn89jpHvCxdnGm+UevShUdsIGRICwtgHz0XToxbhvIW4QauvSiMbgszfBl0dqJGBPLHKxJpgobfAfq1ouvyLTjyvZXluPeXDoUjeseMuOfSFLn+bDAO3HW1b5C+lah6+vTyek0snPkmcNoG7BYx+ypEiNXT92RUNVeiuERL0IM+Cs5FU54qmndXM1I8KsRfL26ZZEkQkXt2xjzgXcUyxNZC246lZAwgXyDUMG8OiJ1H5I9yJ7XNjxeKxlR8lpqMeJcmrWgM91AqIKHFgum1vcik="
    - secure: "SFzHfg4il1DVHbN7jfpkb+roPq2XQgV3M6YPA9WrTjjIiReqLrUjBaePgGWPfvdLOTF1YfQZjxPVCjURXa8CmHiT06ZCvSAUydNL4Ldl8iemCqqw0f5uapvMz8DYhCPVGFB3Ya1wB4+0r924JcxCFdUQhPl0zOu4AP2Z+WHMtk33HJqWzj/n/Bj3Ni8ccNSu5go8obO0NXUfgyGoZwXVCWBN/LpndRgSXE4ViGDe09loYqiDZwKhF4+NkgPRTXkCkqGj3u7T1ZFltyJT79raZrdZdY5qouETLTcWq2HfAhKC0277fTNKY0qqUYqgG+xk8Kxct7itJojf+NRGode64Xxrq0+RYgXTm1JwxQ+px6Rorf8RiWbqfDFoFZaaW+tJhAQzgvODT75728fJbWqA9iTBZys22MUedaf/R6ZDPsDmMlFh1Ush8ML7O+vC/R6laRa/9I2Qz43QWvSAvykSwxS8j/gEYFxvmCF4O7ZcaD/NQH5bPLAtOj7G4r2pj0Ll623rfsFDjD9A+INsaRZfMoAZuq2tlNMp727UaqesfWPV3MgnGHyBBeln+g4rf3Wffumq48juXEb09qcWCqJoHaYoLKI0bzegcZpdcxO2vgG2S4kKOqV+EJh+d61vogzxrkeEaWuzYUMTpNwGoazK4PjktsAY0JvbBUhvsBD9dio="
